### ISSUE TITLE
Compile error under GHC 9.2.3

### ISSUE THREAD

**Issue by clintonmead** [arowM/heterocephalus#32]
Attempting to compile in GHC 9.2.3 results in the following error:

```
src/Text/Heterocephalus.hs:578:11: error:
    • Couldn't match expected type ‘Pat’
                  with actual type ‘[Pat] -> Pat’
    • Probable cause: ‘ConP’ is applied to too few arguments
      In the expression: ConP (mkConName con) patterns
      In the first argument of ‘return’, namely
        ‘(ConP (mkConName con) patterns, concat scopes)’
      In a stmt of a 'do' block:
        return (ConP (mkConName con) patterns, concat scopes)
    |
578 |   return (ConP (mkConName con) patterns, concat scopes)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Heterocephalus.hs:578:32: error:
    • Couldn't match type ‘Pat’ with ‘Language.Haskell.TH.Syntax.Type’
      Expected: [Language.Haskell.TH.Syntax.Type]
        Actual: [Pat]
    • In the second argument of ‘ConP’, namely ‘patterns’
      In the expression: ConP (mkConName con) patterns
      In the first argument of ‘return’, namely
        ‘(ConP (mkConName con) patterns, concat scopes)’
    |
578 |   return (ConP (mkConName con) patterns, concat scopes)
    |                                ^^^^^^^^
```

I believe this is because of the the extra argument now to the `ConP` constructor.

It used to be:

```
ConP [Name] [Pat]
```

But is now:

```
ConP [Name] [Type] [Pat]
```

Just replacing any `ConP x y` call with `ConP x [] y` should allow Heterocephalus to compile again, although you may want to actually parse the new potential type application arguments.

**Comment by arowM** [comment]
Thanks.🌷
Can I ask you to create a PR?
It would be very helpful if you could do it.

**Comment by clintonmead** [comment]
I'll give it a go!

**Comment by arowM** [comment]
Cool!

**Comment by clintonmead** [comment]
Pull request created [here](https://github.com/arowM/heterocephalus/pull/33)  (I'm not sure how to link the issue and PR sorry)

**Comment by arowM** [comment]
I've released new version that supports major three versions of GHC.
https://hackage.haskell.org/package/heterocephalus-1.0.5.7
