### ISSUE TITLE
Does not work with GHC 9.0.2

### ISSUE THREAD

**Issue by kindaro** [arowM/heterocephalus#30]
<details>
<summary><code>cabal build --with-compiler ghc-9.0.2</code></summary>

```
% cabal build --with-compiler ghc-9.0.2
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - heterocephalus-1.0.5.4 (lib) (first run)
Preprocessing library for heterocephalus-1.0.5.4..
Building library for heterocephalus-1.0.5.4..
[6 of 6] Compiling Text.Heterocephalus ( src/Text/Heterocephalus.hs, /tmp/heterocephalus-1.0.5.4/dist-newstyle/build/x86_64-linux/ghc-9.0.2/heterocephalus-1.0.5.4/build/Text/Heterocephalus.o, /tmp/heterocephalus-1.0.5.4/dist-newstyle/build/x86_64-linux/ghc-9.0.2/heterocephalus-1.0.5.4/build/Text/Heterocephalus.dyn_o )

src/Text/Heterocephalus.hs:498:10: error:
    • Couldn't match type ‘[Stmt] -> Exp’ with ‘Exp’
      Expected: Q Exp
        Actual: Q ([Stmt] -> Exp)
    • In the expression: return $ DoE $ map NoBindS exps
      In a case alternative: _ -> return $ DoE $ map NoBindS exps
      In a stmt of a 'do' block:
        case exps of
          [] -> [| return () |]
          [x] -> return x
          _ -> return $ DoE $ map NoBindS exps
    |
498 |     _ -> return $ DoE $ map NoBindS exps
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Heterocephalus.hs:498:25: error:
    • Couldn't match expected type: Maybe
                                      Language.Haskell.TH.Syntax.ModName
                  with actual type: [Stmt]
    • In the second argument of ‘($)’, namely ‘map NoBindS exps’
      In the second argument of ‘($)’, namely ‘DoE $ map NoBindS exps’
      In the expression: return $ DoE $ map NoBindS exps
    |
498 |     _ -> return $ DoE $ map NoBindS exps
    |                         ^^^^^^^^^^^^^^^^
```

</details>

Seems to be a Template Haskell issue. I am working on a patch.
